# Generated by Django 6.1.1 on 2026-09-26 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Bangla or English, e.g. 'বার্ষিক পরীক্ষার সময়সূচি'", max_length=255)),
                ('body', models.TextField(help_text='Full notice text — Bangla unicode supported natively.')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EXAM', 'Exam'), ('ADMISSION', 'Admission'), ('HOLIDAY', 'Holiday'), ('RESULT', 'Result'), ('URGENT', 'Urgent')], default='GENERAL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin_to_top', models.BooleanField(default=False)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pin_to_top', '-published_at'],
            },
        ),
    ]
