# Generated by Django 6.1.1 on 2026-09-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='The single class teacher responsible for this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of_sections', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Leave blank for classes that aren't grouped yet (typically 6-8).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.group'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='applicable_classes',
            field=models.ManyToManyField(blank=True, help_text='Which classes (6-10) this subject is taught in.', related_name='subjects', to='academics.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('academic_year', 'school_class', 'name', 'group')},
        ),
    ]
