# Generated by Django 6.1.1 on 2026-09-26 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='Bangladesh', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(choices=[('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('BUDDHIST', 'Buddhist'), ('CHRISTIAN', 'Christian'), ('OTHER', 'Other')], default='ISLAM', max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Unknown')], max_length=3)),
                ('roll_no', models.PositiveIntegerField(help_text='Roll number within the section for the year.')),
                ('registration_no', models.CharField(help_text='Permanent board/school registration number.', max_length=30, unique=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred out'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('DROPPED', 'Dropped out')], default='ACTIVE', max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('father_occupation', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('mother_occupation', models.CharField(blank=True, max_length=150)),
                ('guardian_relation', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other')], default='FATHER', help_text='Who the primary contact guardian is, if not living with parents.', max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('optional_fourth_subject', models.ForeignKey(blank=True, help_text="The student's chosen 4th/optional subject (bonus GPA point).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_taking_as_fourth', to='academics.subject')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
            ],
            options={
                'ordering': ['section', 'roll_no'],
                'indexes': [models.Index(fields=['section', 'roll_no'], name='students_st_section_60a714_idx'), models.Index(fields=['registration_no'], name='students_st_registr_5bb7fe_idx')],
                'unique_together': {('section', 'roll_no')},
            },
        ),
    ]
