# Generated by Django 6.1.1 on 2026-09-26 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('ID_CARD', 'Student ID Card'), ('REGISTRATION_CARD', 'Registration Card'), ('ADMIT_CARD', 'Admit Card'), ('TESTIMONIAL', 'Testimonial')], max_length=30)),
                ('language', models.CharField(choices=[('EN', 'English'), ('BN', 'Bangla')], default='EN', help_text='Only meaningful for TESTIMONIAL; EN/BN otherwise ignored.', max_length=2)),
                ('file', models.FileField(upload_to='generated_documents/%Y/%m/%d/')),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('filter_summary', models.CharField(blank=True, help_text="Human-readable description of the filters used, e.g. 'Class 10 - Section A - Science'.", max_length=255)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_admit_cards', to='exams.exam')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
