# Generated by Django 6.1.1 on 2026-09-26 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('HEADTEACHER', 'Headteacher'), ('ASSISTANT_HEADTEACHER', 'Assistant Headteacher'), ('SENIOR_TEACHER', 'Senior Teacher'), ('ASSISTANT_TEACHER', 'Assistant Teacher'), ('STAFF', 'Non-teaching Staff')], max_length=30)),
                ('education_qualification', models.CharField(blank=True, help_text='e.g. M.Sc in Physics, B.Ed', max_length=255)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('assigned_sections', models.ManyToManyField(blank=True, help_text='Class-sections this teacher currently takes classes in.', related_name='subject_teachers', to='academics.section')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subject(s) this teacher is qualified/assigned to teach.', related_name='teachers', to='academics.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
