# Generated by Django 6.1.1 on 2026-09-26 11:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('CLASS_TEST', 'Class Test'), ('FIRST_TERM', 'First Term / Half Yearly'), ('SECOND_TERM', 'Second Term'), ('PRE_TEST', 'Pre-Test'), ('TEST_EXAM', 'Test Exam (Pre-SSC)'), ('FINAL', 'Final / Annual Exam'), ('SSC', 'SSC Board Exam')], max_length=20)),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_pass', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'ordering': ['-exam__date'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cq_obtained', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('mcq_obtained', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('practical_obtained', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('total_obtained', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to='teachers.teacher')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_entries', to='academics.subject')),
            ],
            options={
                'ordering': ['exam', 'student', 'subject'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
